### ISSUE TITLE
No Tooltip

### ISSUE THREAD

**Issue by Yabbadabbadouh** [gonzoinc/Disenchanter#23]
Hey,
i get absolute no tooltip. Even if i disable ALL other Addons (except Ace3 & Disenchanter). 
There is no tt for the materials. But i see the expansion ^^

![tooltip](https://user-images.githubusercontent.com/120409849/215331231-6e9087b2-123f-4423-b352-2c9c71ef8b54.jpg)

**Comment by gonzoinc** [comment]
This is a language setting issue. The addon matches string text data for itype in English. Your UI is set to German so the string data will not match. The expansion portion is working as it is detected on integers. The addon localization supports english only.
