### ISSUE TITLE
Won't let me disenchant. have to /reload to fix.

### ISSUE THREAD

**Issue by Zoid1244** [gonzoinc/Disenchanter#24]
Date: 2023-03-01 19:11:54
ID: -1
Error occured in: AddOn: Disenchanter
Count: 9
Message: Error: AddOn Disenchanter attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: UseContainerItem()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1402:
      Interface/FrameXML/ContainerFrame.lua:1311
   [string "=[C]"]: ContainerFrameItemButton_OnClick()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1454:
      Interface/FrameXML/ContainerFrame.lua:1441
Locals:
None
AddOns:
  Swatter, v9.1.BETA.5.10 (OneMawTime)
  Ace3, vr1300
  AddonFactory, v10.0.011
  AllTheThings, vDF-3.2.5
  Altoholic, v10.0.011
  Annene, vv10.0.2-2
  APR, vv2.1.12
  APRBattleForAzeroth, v
  APRCore, v
  APRDragonflight, v
  APRExilesReach, v
  APRLegion, v
  APRMistsOfPandaria, v
  APRShadowlands, v
  APRTheBurningCrusade, v
  APRVanilla, v
  APRWarlordsOfDraenor, v
  APRWrathOfTheLichKing, v
  AskMrRobot, v121
  Auctionator, v10.0.39
  Auctioneer, v9.1.BETA.5.10 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.10 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.10 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.10 (OneMawTime)
  BattlePetDailyTamer, v3.2.3
  BattlePetBattleUITweaks, v2.1.5
  BattlePetBreedID, vv1.22.9
  BattlePetCageMatch, v3.5
  BrokerPortals, v1.11.11
  ChampionCommander, v1.4.2 100002
  Collectionator, v0.106
  CollectMe, v2.12
  CovenantMissionHelper, v3.2.0
  DataStore, v2023.02.23
  DataStoreAchievements, v2023.02.23
  DataStoreAgenda, v10.0.011
  DataStoreAuctions, v10.0.011
  DataStoreCharacters, v2023.02.23
  DataStoreContainers, v10.0.011
  DataStoreCrafts, v10.0.011
  DataStoreCurrencies, v10.0.011
  DataStoreGarrisons, v10.0.011
  DataStoreInventory, v10.0.011
  DataStoreMails, v2023.02.23
  DataStorePets, v10.0.011
  DataStoreQuests, v10.0.011
  DataStoreReputations, v10.0.011
  DataStoreSpells, v2023.02.23
  DataStoreStats, v10.0.011
  DataStoreTalents, v10.0.011
  DBMCore, v3f5f99b
  DBMCountPackHotS, v1.7.24
  DBMInterrupts, v2.5.3
  DBMSMGEventsPack, v1.5.23
  DBMSoundEventsPack, v1.6.22
  DBMSpellTimers, vr145
  DBMStatusBarTimers, v3f5f99b
  DBMVPVEM, vc400d2c
  Details, v#Details.DF.Wrath.10.0.5.10661.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Disenchanter, vv1.1.5
  Enchantrix, v9.1.BETA.5.10 (OneMawTime)
  FarmHud, v9.1.1-release
  FarmHudQuestArrow, v9.1.1-release
  FarmHudTrailPath, v9.1.1-release
  GarrisonCommander, v3.4.1 100002
  GarrisonCommanderBroker, v3.4.1 100002
  GatherMate2, v1.48.3
  GreenWall, v1.11.9
  GTFO, v5.0.5
  HandyNotes, vv1.6.13
  HandyNotesLunarFestival, v1.11
  HandyNotesMistsOfPandariaTreasures, vv25
  HandyNotesShadowlands, v53
  HandyNotesSuramarShalAranTelemancy, vv1.43
  HandyNotesTravelGuide, vv2.14.1
  HandyNotesTreasureHunter, vv33
  Hekili, vv10.0.5-1.0.20
  HereBeDragons, v2.12-release
  HHTD, v2.4.10
  Informant, v9.1.BETA.5.10 (OneMawTime)
  InviteOnWhisper, vv1.4.18
  Journalator, v1.25
  MinimapButtonButton, v1.14.3
  MoveAny, v1.0.60
  MRT, v4720
  OrderHallCommander, v1.10.1 100002
  Pawn, v2.7.16
  PersoLootRoll, v24.03
  PetTracker, v10.0.1
  PetTrackerBattle, v
  PetTrackerJournal, v
  PowerfulAlts, v1.03
  QuestCompletist, v109.42
  QuestPointer, vv29
  RareScanner, v10.0.5.4
  Rarity, v1.0 (r719-alpha)
  RarityOptions, v
  Rematch, v4.14.13
  RematchTSMPetValues, v1.1.30
  Routes, vv1.7.4
  RoutesImportExport, vv1.0.7
  SharedMediaCausese, v
  Simulationcraft, v10.0.5-01
  SlideBar, v9.1.BETA.5.10 (OneMawTime)
  SmexyMats, v10.0.0.2 Retail
  Stubby, v9.1.BETA.5.10 (OneMawTime)
  tdBattlePetScript, vv1.5
  TLDRMissions, v10.0-013
  TomCats, v2.4.55
  TomeOfTeleportation, v
  TomTom, vv3.3.5-release
  TyllusMapPin, v
  UltraSquirt, v0.9.6
  WeakAuras, v5.3.7
  WhereToGather, v0.14.2
  WIM, v3.10.9
  WorldFlightMap, v10.0.0.0
  WorldQuestTracker, vv10.0.5.463-Retail
  ZerethMortisPuzzleHelper, v1.6.3
  BlizRuntimeLib_enUS v10.0.5.100005 <none>
  (ck=dad)

**Comment by gonzoinc** [comment]
The issue is coming from another addon tainting the path calling UseContainerItem(). Unfortunately the logger doesn't show what addon tainted the path but my guess would be some addon that interacts with your bags. The Disenchanted addon doesn't use the UseContainerItem call so I'm 100% sure the issue is not on my end.  

Best bet would be to disable all addons and enable disenchanter, then enable each one to see what is tainting the path originally. Most likely something that was recently updated is causing the issue so maybe look at what addons updated recently and start there.
