### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by tmr-jay** [gonzoinc/Disenchanter#29]
back to WoW after ages away. love this AddOn, but couldnt see anywhere in SourceForge app, nor in the documentation including ReadMe, that it required Ace3 library to also be installed. I'm all good after finding an issue where that library was mentioned.

suggest adding the apps dependencies somewhere in documentation.

thanks

**Comment by gonzoinc** [comment]
It is defined as an external dependency in the pkgmeta file so it should be auto installed when using any addon manager IE: curseforge, wowup, etc.  Adding a note for those brave enough to try to manage add-ons manually.
